### ISSUE TITLE
Getting invalid-meta error for bower install get-node-dimensions --save

### ISSUE THREAD

**Issue by ghost** [souporserious/get-node-dimensions#3]
Looks like it doesn't like having both a minified and standard file type. 

`Macintosh-471:get-node-dimensions admin$ bower install get-node-dimensions --save
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["./dist/get-node-dimensions.js","./dist/get-node-dimensions.min.js"]
bower ENOTFOUND     Package get-node-dimensions not found
`

**Comment by souporserious** [comment]
My bad, I meant to remove that in favor of this https://unpkg.com/get-node-dimensions/dist/get-node-dimensions.js
